feat: GStreamer pipeline to send MuJoCo frames with WebRTC to a browser (#380)
* initial fastapi scaffold

* feat: added evolve and replay endpoints for the API

* feat: containerized TPG + FastAPI and able to call endpoints locally

* Squashed 'src/src/playground/' content from commit 5cb0e380

git-subtree-dir: src/src/playground
git-subtree-split: 5cb0e3806a0f0b3ebde666942c181a553c781e11

* chore: remove git subtree

* WIP: dockerfile but fixed returns for evolve API end point

* WIP: Dockefile build of TPG + Engine

* WIP: Dockerfile build to run tpg CLI in containerized environments

* WIP: dockerfile

* fix: enable localhost to bypass CORS

* WIP: webrtc signaling server skeleton

* added GStreamer packages to requirements.txt

* WIP: setting up GStreamer pipeline for real time processing

* feat: created frame capture pipeline with GStreamer

* feat: frames are able to be pushed with fakesink

* WIP: trying to create GStreamer pipeline with webrtcbin

* feat: GStreamer pipeline able to construct WebRTC pipeline

* WIP: initial skeleton for signaling server routing

* WIP: GStreamer pipeline connection to frontend

* WIP: debugging frames not being sent over the signaling server

* WIP: edit JSON messages to include id, no ice candidates generated

* fix: ice candidate generation from C++ side

* WIP: integrated GMainLoop

* fix: allow GStreamer pipeline to receive messages from web socket server

* fix: able to parse ICE candidate response from web socket

* fix: ice candidate handling in GStreamer pipeline, can see RTP packets being sent

* fix: inverted frames pushed to pipeline

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -37,6 +37,15 @@ optimized:
 	@cd $(TPG) && $(CMAKE) -B $(BUILD_DIR) -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_HIGH_OPTIMIZATION=ON
 	@cd $(TPG) && $(CMAKE) --build $(BUILD_DIR)
 
+# Release build with high optimization and livestreaming enabled with WebRTC
+livestream:
+	@if [ -z "$(TPG)" ]; then \
+		echo "ERROR: TPG environment variable is not set"; \
+		exit 1; \
+	fi
+	@cd $(TPG) && $(CMAKE) -B $(BUILD_DIR) -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_HIGH_OPTIMIZATION=ON -DENABLE_LIVE_STREAMING=ON
+	@cd $(TPG) && $(CMAKE) --build $(BUILD_DIR)
+
 # Clean the build directory
 clean:
 	@if [ -z "$(TPG)" ]; then \
